INSERT INTO ADDRESS (NAME, CELL_PHONE, UPDATE_TIME, CREATE_TIME)
VALUES ('홍길동', '01011112222', NOW(), NOW());
INSERT INTO ADDRESS (NAME, CELL_PHONE, UPDATE_TIME, CREATE_TIME)
VALUES ('다비치', '01033334444', NOW(), NOW());
INSERT INTO ADDRESS (NAME, CELL_PHONE, UPDATE_TIME, CREATE_TIME)
VALUES ('더콰이엇', '01055556666', NOW(), NOW());
